run:
  deadline: 60s
  issues-exit-code: 1
  tests: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  print-welcome: true

linters:
  enable-all: true
  disable:
    - dupl
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - golint
    - interfacer
    - maligned
    - megacheck
