language: go
sudo: required

git:
  depth: 1

osx_image: xcode9.1

matrix:
  allow_failures:
    - go: master
  fast_finish: true
  include:
    - os: linux
      go:
        - 1.9.x
        - master
        - go1.10beta2
      allow_failures:
        - go: master
        - go: go1.10beta2
    - os: osx
      go:
        - 1.9.x

script:
  - make ci

services:
  - docker
