package lib

/////////////////////////////////////////////////////////////////
//Code generated by chidley https://github.com/gnewton/chidley //
/////////////////////////////////////////////////////////////////

import (
	"bufio"
	"compress/bzip2"
	"compress/gzip"
	"encoding/json"
	"encoding/xml"
	"flag"
	"fmt"
	"io"
	"log"
	"os"
	"runtime"
	"strings"
)

const (
	JsonOut = iota
	XmlOut
	CountAll
)

var toJson bool = true // was false
var toXml bool = false
var oneLevelDown bool = false
var countAll bool = false
var musage bool = false

var uniqueFlags = []*bool{
	&toJson,
	&toXml,
	&countAll}

var filename = "/Users/adam/src/go/src/github.com/adamdecaf/cert-manage/testdata/Admin2.plist"



func init() {
	flag.BoolVar(&toJson, "j", toJson, "Convert to JSON")
	flag.BoolVar(&toXml, "x", toXml, "Convert to XML")
	flag.BoolVar(&countAll, "c", countAll, "Count each instance of XML tags")
	flag.BoolVar(&oneLevelDown, "s", oneLevelDown, "Stream XML by using XML elements one down from the root tag. Good for huge XML files (see http://blog.davidsingleton.org/parsing-huge-xml-files-with-go/")
	flag.BoolVar(&musage, "h", musage, "Usage")
	flag.StringVar(&filename, "f", filename, "XML file or URL to read in")
}

var out int = -1

var counters map[string]*int

func main() {
	runtime.GOMAXPROCS(runtime.NumCPU())
	flag.Parse()

	if musage {
		flag.Usage()
		return
	}

	numSetBools, outFlag := numberOfBoolsSet(uniqueFlags)
	if numSetBools == 0 {
		flag.Usage()
                return
	}

	if numSetBools != 1 {
		flag.Usage()
		log.Fatal("Only one of ", uniqueFlags, " can be set at once")
	}

	reader, xmlFile, err := genericReader(filename)
	if err != nil {
		log.Fatal(err)
		return
	}

	decoder := xml.NewDecoder(reader)
	counters = make(map[string]*int)
	for {
		token, _ := decoder.Token()
		if token == nil {
			break
		}
		switch se := token.(type) {
		case xml.StartElement:
			handleFeed(se, decoder, outFlag)
		}
	}
        if xmlFile != nil{
	    defer xmlFile.Close()
        }
	if countAll {
		for k, v := range counters {
			fmt.Println(*v, k)
		}
	}
}

func handleFeed(se xml.StartElement, decoder *xml.Decoder, outFlag *bool) {
	fmt.Println("A")

	if outFlag == &countAll {
		fmt.Println("AA")
		incrementCounter(se.Name.Space, se.Name.Local)
	} else {
		fmt.Println("BB")
                if !oneLevelDown{
			fmt.Println("BBB")
			fmt.Printf("se.Name.Local = %s\n", se.Name.Local)
			fmt.Printf("se.Name.Space = %s\n", se.Name.Space)
        		if se.Name.Local == "plist" && se.Name.Space == "" {
	        	      var item Chiplist
			      decoder.DecodeElement(&item, &se)
			      switch outFlag {
			      case &toJson:
				      fmt.Println("B")
				      writeJson(item)
			      case &toXml:
				      writeXml(item)
			      }
		      }
                } else {
			fmt.Println("CCC")
        		if se.Name.Local == "dict" && se.Name.Space == "" {
	        	      var item Chidict
			      decoder.DecodeElement(&item, &se)
			      switch outFlag {
			      case &toJson:
				      fmt.Println("C")
				      writeJson(item)
			      case &toXml:
				      writeXml(item)
			      }
		      }

               }
	}
}

func makeKey(space string, local string) string {
	if space == "" {
		space = "_"
	}
	return space + ":" + local
}

func incrementCounter(space string, local string) {
	key := makeKey(space, local)

	counter, ok := counters[key]
	if !ok {
		n := 1
		counters[key] = &n
	} else {
		newv := *counter + 1
		counters[key] = &newv
	}
}

func writeJson(item interface{}) {
	b, err := json.MarshalIndent(item, "", " ")
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(string(b))
}

func writeXml(item interface{}) {
	output, err := xml.MarshalIndent(item, "  ", "    ")
	if err != nil {
		fmt.Printf("error: %v\n", err)
	}
	os.Stdout.Write(output)
}

func genericReader(filename string) (io.Reader, *os.File, error) {
	if filename == "" {
		return bufio.NewReader(os.Stdin), nil, nil
	}
	file, err := os.Open(filename)
	if err != nil {
		return nil, nil, err
	}
	if strings.HasSuffix(filename, "bz2") {
		return bufio.NewReader(bzip2.NewReader(bufio.NewReader(file))), file, err
	}

	if strings.HasSuffix(filename, "gz") {
		reader, err := gzip.NewReader(bufio.NewReader(file))
		if err != nil {
			return nil, nil, err
		}
		return bufio.NewReader(reader), file, err
	}
	return bufio.NewReader(file), file, err
}

func numberOfBoolsSet(a []*bool) (int, *bool) {
	var setBool *bool
	counter := 0
	for i := 0; i < len(a); i++ {
		if *a[i] {
			counter += 1
			setBool = a[i]
		}
	}
	return counter, setBool
}


///////////////////////////
/// structs
///////////////////////////

type Chiroot struct {
	Chiplist *Chiplist `xml:" plist,omitempty" json:"plist,omitempty"`
}

type Chiplist struct {
	Attr_version string `xml:" version,attr"  json:",omitempty"`
	Chidict *Chidict `xml:" dict,omitempty" json:"dict,omitempty"`
}

type Chidict struct {
	Chiarray *Chiarray `xml:" array,omitempty" json:"array,omitempty"`
	Chidata []*Chidata `xml:" data,omitempty" json:"data,omitempty"`
	Chidate *Chidate `xml:" date,omitempty" json:"date,omitempty"`
	Chidict *Chidict `xml:" dict,omitempty" json:"dict,omitempty"`
	Chiinteger []*Chiinteger `xml:" integer,omitempty" json:"integer,omitempty"`
	Chikey []*Chikey `xml:" key,omitempty" json:"key,omitempty"`
}

type Chikey struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type Chidata struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type Chidate struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type Chiarray struct {
	Chidict *Chidict `xml:" dict,omitempty" json:"dict,omitempty"`
}

type Chiinteger struct {
	Text string `xml:",chardata" json:",omitempty"`
}


///////////////////////////

// Generated under -G -X flags
// type Chiroot struct {
// 	Chiplist *Chiplist `xml:"plist"`
// }

// type Chiplist struct {
// 	Attr_version string `xml:"version,attr" `
// 	Chidict *Chidict `xml:"dict"`
// }

// type Chidict struct {
// 	Chiarray *Chiarray `xml:"array"`
// 	Chidata []*Chidata `xml:"data"`
// 	Chidate *Chidate `xml:"date"`
// 	Chidict *Chidict `xml:"dict"`
// 	Chiinteger []*Chiinteger `xml:"integer"`
// 	Chikey []*Chikey `xml:"key"`
// }

// type Chikey struct {
// 	Text string `xml:"key"`
// }

// type Chidata struct {
// 	Text string `xml:"data"`
// }

// type Chidate struct {
// 	Text string `xml:"date"`
// }

// type Chiarray struct {
// 	Chidict *Chidict `xml:"array"`
// }

// type Chiinteger struct {
// 	Text string `xml:"integer"`
// }
